apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "http-app.fullname" . }}
  labels:
    {{- include "http-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "http-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "http-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "http-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}