apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "http-app.fullname" . }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "http-app.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
