version: '3'
services:
  backend:
    image: backend-service
    deploy:
      replicas: 2
    networks:
      - loadbalancing

  nginx:
    image: nginx-service
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - backend

networks:
  loadbalancing: