version: '3'
services:
  http-app:
    image: http-app:1.0.0
    deploy:
      replicas: 2
    networks:
      - loadbalancing

  nginx:
    image: nginx-service
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - http-app

networks:
  loadbalancing: